Requirements fix
bigscience-workshop/biomedical pull request #167
Opened 2022-03-01 12:00 UTC by nomisto

pip<=20.3 allows only one top level specification of a requirement. Requirements however specifies `huggingface_hub` two times. fixes #132

Futher info: https://github.com/pypa/pip/issues/2367, https://github.com/pypa/pip/issues/988

2022-03-02 00:06 UTC, galtay requested changes
both `datasets` and `transformers` use `huggingface_hub>=0.1.0,<1.0.0`

* https://github.com/huggingface/transformers/blob/master/setup.py#L111
* https://github.com/huggingface/datasets/blob/master/setup.py#L99

I'm not sure if those requirements are stale, but perhaps we should follow that example for now? thanks for finding the double requirement!

2022-03-02 09:41 UTC, nomisto commented
Sure, sounds good! I've changed the huggingface_hub version specifier to that of datasets. It would however be good to know what the reason was for `huggingface_hub>=0.4.0` in the first place in https://github.com/bigscience-workshop/biomedical/commit/9c8d2794b1828e8f08f11e4dc4fb3cd76ec4884d, not that we are introducing some bug again.

2022-03-02 17:27 UTC, galtay-tempus commented
@hakunanatasha thoughts here?

2022-03-03 17:06 UTC, galtay-tempus approved these changes
Going to merge the versioning that is consistent with `datasets` and `transformers` for now, but we can change to `>=0.4.0` if we need to later.

2022-03-03 17:06 UTC, galtay-tempus approved these changes

2022-03-03 17:07 UTC, merged