Add dataloader for MedDialog
bigscience-workshop/biomedical pull request #329
Opened 2022-04-04 23:07 UTC by j-chim

Please name your PR after the issue it closes. You can use the following line: "Closes #ISSUE-NUMBER" where you replace the ISSUE-NUMBER with the one corresponding to your dataset.

If the following information is NOT present in the issue, please populate:

- **Name:** *name of the dataset*
- **Description:** *short description of the dataset (or link to social media or blog post)*
- **Paper:** *link to the dataset paper if available*
- **Data:** *link to the online home of the dataset*

### Checkbox

- [ ] Confirm that this PR is linked to the dataset issue.
- [ ] Create the dataloader script `biodatasets/my_dataset/my_dataset.py` (please use only lowercase and underscore for dataset naming).
- [ ] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_BIGBIO_VERSION` variables.
- [ ] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [ ] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `BigBioConfig` for the source schema and one for a bigbio schema.
- [ ] Confirm dataloader script works with `datasets.load_dataset` function.
- [ ] Confirm that your dataloader script passes the test suite run with `python -m tests.test_bigbio biodatasets/my_dataset/my_dataset.py`.

2022-04-05 04:37 UTC, galtay requested changes
Thanks for helping us work through the task/schema issues. Lets try this as a text classification task with each (utterance, speaker) tuple as a (text, label) pair.

2022-04-05 04:37 UTC, galtay commented on biodatasets/meddialog/meddialog.py
> +            subset_id="meddialog",
I think we should make each language a subset id 
```suggestion
            subset_id="meddialog_en",
```

2022-04-05 04:37 UTC, galtay commented on biodatasets/meddialog/meddialog.py
> +            subset_id="meddialog",
```suggestion
            subset_id="meddialog_zh",
```

2022-04-05 04:37 UTC, galtay commented on biodatasets/meddialog/meddialog.py
> +    ]
good idea, lets implement these.

2022-04-05 08:39 UTC, j-chim commented
Thanks @galtay, have incorporated the comments. 

The main concern I have is with the missing descriptions. In this dataset, for English only, there's a "descriptions" that provides context for the utterances. If there is a way to add an optional context field it would be great, e.g., treat each classification instance as a (text, label, context). Have added this in the suggestions channel.

2022-04-05 23:10 UTC, galtay commented
Thanks for the suggestions in the discord channel! I think we should definitely keep those schema updates in mind for future iterations / hackathons. I think the source schema leaves a lot of options open for users of this dataset loader. For the moment, I'd like to merge this with the text classification as implemented and revisit when we have a more suitable schema. Does that work for you?

2022-04-05 23:20 UTC, j-chim commented
> Thanks for the suggestions in the discord channel! I think we should definitely keep those schema updates in mind for future iterations / hackathons. I think the source schema leaves a lot of options open for users of this dataset loader. For the moment, I'd like to merge this with the text classification as implemented and revisit when we have a more suitable schema. Does that work for you?

Yes this sounds great, thanks @galtay

2022-04-06 00:05 UTC, galtay approved these changes

2022-04-06 00:06 UTC, galtay commented
this PR got caught in the middle of a schema change we made for text classification  but I will merge this and then update it.

2022-04-06 00:06 UTC, merged