First commit of MeDAL dataset loader- not working yet, committing and creating PR so as to debug
bigscience-workshop/biomedical pull request #450
Opened 2022-04-13 20:57 UTC by alisoncallahan

Please name your PR after the issue it closes. You can use the following line: "Closes #ISSUE-NUMBER" where you replace the ISSUE-NUMBER with the one corresponding to your dataset.

If the following information is NOT present in the issue, please populate:

- **Name:** *name of the dataset*
- **Description:** *short description of the dataset (or link to social media or blog post)*
- **Paper:** *link to the dataset paper if available*
- **Data:** *link to the online home of the dataset*

### Checkbox

- [x ] Confirm that this PR is linked to the dataset issue.
- [ x] Create the dataloader script `biodatasets/my_dataset/my_dataset.py` (please use only lowercase and underscore for dataset naming).
- [ x] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_BIGBIO_VERSION` variables.
- [ x] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [ x] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `BigBioConfig` for the source schema and one for a bigbio schema.
- [ ] Confirm dataloader script works with `datasets.load_dataset` function.
- [ ] Confirm that your dataloader script passes the test suite run with `python -m tests.test_bigbio biodatasets/my_dataset/my_dataset.py`.
- [ ] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

2022-04-13 21:12 UTC, jason-fries requested changes

2022-04-13 21:12 UTC, jason-fries commented on biodatasets/medal/medal.py
> +            features=datasets.Features(
Remove the trailing comma :) 

```
        if self.config.schema == "source":
            features = datasets.Features(
                {
                    "abstract_id": datasets.Value("int32"),
                    "text": datasets.Value("string"),
                    "location": datasets.Sequence(datasets.Value("int32")),
                    "label": datasets.Sequence(datasets.Value("string")),
                }
            )
```

2022-04-13 21:13 UTC, alisoncallahan commented on biodatasets/medal/medal.py
> +            features=datasets.Features(
I did, still the same issue.

2022-04-13 21:17 UTC, alisoncallahan commented on biodatasets/medal/medal.py
> +            features=datasets.Features(
Thanks! That fixed it.

2022-04-21 22:18 UTC, jason-fries commented
This PR is getting thorny -- deleting so @alisoncallahan can just push a fresh one.

2022-04-21 22:18 UTC, closed without merging