First draft of MedNLI dataloader
bigscience-workshop/biomedical pull request #467
Opened 2022-04-15 15:22 UTC by JohnGiorgi

Please name your PR after the issue it closes. You can use the following line: "Closes #ISSUE-NUMBER" where you replace the ISSUE-NUMBER with the one corresponding to your dataset.

If the following information is NOT present in the issue, please populate:

- **Name:** MedNLI
- **Description:** MedNLI - a dataset annotated by doctors, performing a natural language inference task (NLI),
grounded in the medical history of patients.
- **Paper:** https://physionet.org/content/mednli/1.0.0/
- **Data:** https://physionet.org/content/mednli/1.0.0/

### Checkbox

- [ ] Confirm that this PR is linked to the dataset issue.
- [ ] Create the dataloader script `biodatasets/my_dataset/my_dataset.py` (please use only lowercase and underscore for dataset naming).
- [ ] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_BIGBIO_VERSION` variables.
- [ ] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [ ] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `BigBioConfig` for the source schema and one for a bigbio schema.
- [ ] Confirm dataloader script works with `datasets.load_dataset` function.
- [ ] Confirm that your dataloader script passes the test suite run with `python -m tests.test_bigbio biodatasets/my_dataset/my_dataset.py`.
- [ ] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

2022-04-15 15:26 UTC, JohnGiorgi commented
Here is the output of the unit tests:

```
python -m tests.test_bigbio biodatasets/mednli/mednli.py --data_dir /Users/johngiorgi/Documents/dev/biomedical/physionet.org/files/mednli/1.0.0
INFO:__main__:args: Namespace(data_dir='/Users/johngiorgi/Documents/dev/biomedical/physionet.org/files/mednli/1.0.0', path='biodatasets/mednli/mednli.py', schema=None, subset_id=None, use_auth_token=None)
INFO:__main__:self.PATH: biodatasets/mednli/mednli.py
INFO:__main__:self.SUBSET_ID: mednli
INFO:__main__:self.SCHEMA: None
INFO:__main__:self.DATA_DIR: /Users/johngiorgi/Documents/dev/biomedical/physionet.org/files/mednli/1.0.0
INFO:__main__:Checking for _SUPPORTED_TASKS ...
INFO:__main__:Found _SUPPORTED_TASKS=[<Tasks.TEXTUAL_ENTAILMENT: 'TE'>]
INFO:__main__:_SUPPORTED_TASKS implies _MAPPED_SCHEMAS={'TE'}
INFO:__main__:schemas_to_check: {'TE'}
INFO:__main__:Checking load_dataset with config name mednli_source
WARNING:datasets.builder:Using custom data configuration mednli_source-e74e1630bc2bbeba
WARNING:datasets.builder:Reusing dataset med_nli_dataset (/Users/johngiorgi/.cache/huggingface/datasets/med_nli_dataset/mednli_source-e74e1630bc2bbeba/1.0.0/1caf5757196c0609c9086428cd2bfb1e7ee9c4534b8e10cdcfb2034a7766d5f5)
100%|█████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 375.99it/s]
INFO:__main__:Checking load_dataset with config name mednli_bigbio_te
WARNING:datasets.builder:Using custom data configuration mednli_bigbio_te-e74e1630bc2bbeba
WARNING:datasets.builder:Reusing dataset med_nli_dataset (/Users/johngiorgi/.cache/huggingface/datasets/med_nli_dataset/mednli_bigbio_te-e74e1630bc2bbeba/1.0.0/1caf5757196c0609c9086428cd2bfb1e7ee9c4534b8e10cdcfb2034a7766d5f5)
100%|█████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 917.19it/s]
INFO:__main__:Checking global ID uniqueness
INFO:__main__:Found 1395 unique IDs
INFO:__main__:Gathering schema statistics
INFO:__main__:Gathering schema statistics
train
==========
id: 11232
premise: 11232
hypothesis: 11232
label: 11232

test
==========
id: 1422
premise: 1422
hypothesis: 1422
label: 1422

validation
==========
id: 1395
premise: 1395
hypothesis: 1395
label: 1395

.
----------------------------------------------------------------------
Ran 1 test in 3.125s

OK
```

2022-04-20 01:14 UTC, galtay requested changes

2022-04-20 01:14 UTC, galtay commented on biodatasets/mednli/mednli.py
> +                    "filepath": os.path.join(data_dir, "mli_train_v1.jsonl"),
in the other local dataset loaders we've tried to use the tar/zip/archive files directly. would it be possible for this script to work directly with the `mednli-a-natural-language-inference-dataset-for-the-clinical-domain-1.0.0.zip` file?

2022-04-20 01:14 UTC, galtay commented on biodatasets/mednli/mednli.py
> +"""
please add some information to the docstring concerning the form that the input should take (e.g. https://github.com/bigscience-workshop/biomedical/blob/master/biodatasets/n2c2_2006_deid/n2c2_2006_deid.py#L34)

2022-04-20 01:15 UTC, galtay requested changes
a few changes about the data_dir and file descriptions please

2022-04-21 01:09 UTC, JohnGiorgi commented
@galtay This has all the same fixes as #468 so I think its ready to merge unless you spot anything?

2022-04-21 01:46 UTC, galtay approved these changes
thank you for working through my confusing requests! LGTM

2022-04-21 01:46 UTC, merged

2022-04-21 02:47 UTC, JohnGiorgi commented
> thank you for working through my confusing requests! LGTM

Thanks for all the feedback!!

2023-05-17 11:34 UTC, NtaylorOX commented
Do you have an example of using this using the load_dataset function? As when I try it fails as seems to not like the data_dir being passed as an argument, 

e.g. 

```
from datasets import load_dataset

data_dir="/mnt/sdd/niallt/mednli-a-natural-language-inference-dataset-for-the-clinical-domain-1.0.0.zip"
dataset = load_dataset("bigbio/mednli", data_dir = data_dir)

```
leads to:

AttributeError: 'BuilderConfig' object has no attribute 'schema'

And the documentation of how to actually provide the data_dir argument is not all that clear from what I can tell.