Closes #220
bigscience-workshop/biomedical pull request #475
Opened 2022-04-16 07:57 UTC by jdposada

Please name your PR after the issue it closes. You can use the following line: "Closes #ISSUE-NUMBER" where you replace the ISSUE-NUMBER with the one corresponding to your dataset.

If the following information is NOT present in the issue, please populate:

- **Name:** *name of the dataset*
- **Description:** *short description of the dataset (or link to social media or blog post)*
- **Paper:** *link to the dataset paper if available*
- **Data:** *link to the online home of the dataset*

### Checkbox

- [ ] Confirm that this PR is linked to the dataset issue.
- [ ] Create the dataloader script `biodatasets/my_dataset/my_dataset.py` (please use only lowercase and underscore for dataset naming).
- [ ] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_BIGBIO_VERSION` variables.
- [ ] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [ ] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `BigBioConfig` for the source schema and one for a bigbio schema.
- [ ] Confirm dataloader script works with `datasets.load_dataset` function.
- [ ] Confirm that your dataloader script passes the test suite run with `python -m tests.test_bigbio biodatasets/my_dataset/my_dataset.py`.
- [ ] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

2022-04-16 07:57 UTC, jdposada commented
Closes #220

2022-04-17 18:48 UTC, galtay commented
@jdposada this is great and the tests pass on my end but I was wondering if you have the bandwidth to split this into two dataset loaders like was done for `n2c2_2006` ? 
* https://github.com/bigscience-workshop/biomedical/tree/master/biodatasets/n2c2_2006_deid
* https://github.com/bigscience-workshop/biomedical/tree/master/biodatasets/n2c2_2006_smokers

2022-04-18 13:30 UTC, jdposada commented
Hi @galtay,

I could do the separation next week, is that ok?

2022-04-18 20:40 UTC, jdposada commented on biodatasets/n2c2_2014/n2c2_2014.py
> +                            pass
Needs fixing @jdposada

2022-04-19 04:50 UTC, galtay commented
> Hi @galtay,
> 
> I could do the separation next week, is that ok?

next week as in the end of the month? that might be a little late ... let's check in this weekend and see where we're at

2022-04-19 04:51 UTC, galtay requested changes
split into task1 and task2 dataset loaders

2022-04-25 05:18 UTC, jason-fries commented
Hey @jdposada 
Just checking in on this PR -- do you have bandwidth to make the requested changes?

2022-05-21 15:58 UTC, ruisi-su commented
Hi @jdposada, just checking on the timeline. Any chance that this could be done before the end of next week? Thanks in advance!

2022-05-27 13:41 UTC, ruisi-su commented
Hi @jdposada, thanks for your hard work in adding this dataset! Any chance that this could be PR-ready by next week? We really need to add this dataset ASAP. Please tell us if you would not be able to have the bandwidth to get this ready. We will need to re-assign the issue. I wanted to check with you first since you have already worked on this for quite a while. Thanks again!

2022-05-27 23:37 UTC, jdposada commented
Hi @ruisi-su , working on it, I understand the urgency and surely will be able to make the PR. I know I missed my past deadline but will firmly commit to this one. Thanks

2022-05-28 00:38 UTC, jdposada commented
I created a different pull request since I am splitting the datasets. The new pull request for deid is here. The risk stratification task is coming

https://github.com/bigscience-workshop/biomedical/pull/644

2022-05-28 12:15 UTC, jdposada commented
Hi @ruisi-su 

I created the second pull request for risk factors here. Let me know if I am missing anything. Thanks

https://github.com/bigscience-workshop/biomedical/pull/646

2022-06-03 14:12 UTC, ruisi-su commented
This PR is closed as the subtasks are addressed in #644 and #646

2022-06-03 14:12 UTC, closed without merging