hallmarks_of_cancer dataset
bigscience-workshop/biomedical pull request #85
Opened 2022-01-31 05:35 UTC by debajyotidatta

2022-02-16 07:37 UTC, jason-fries requested changes
@debajyotidatta Can we update this to the most recent schema format? :)

2022-02-20 04:35 UTC, sunnnymskang commented
@debajyotidatta pinging again to adapt the schema to reflect the most recent format: https://github.com/bigscience-workshop/biomedical/blob/master/schemas/text.py

2022-02-25 18:10 UTC, sunnnymskang requested changes
HI @debajyotidatta Can you change the formatting to agree with the latest template changes? (https://github.com/bigscience-workshop/biomedical/blob/master/templates/template.py) Specifically, there's an explicit "source" in addition to "bigbio" Though it's a cosmetic change, I think it'll be helpful that all examples have uniform formatting that aligns with the template.py

2022-02-25 18:36 UTC, galtay-tempus commented on examples/hallmarks_of_cancer.py
> +            name=_DATASETNAME,
```suggestion
            name="source",
```

2022-02-25 18:36 UTC, galtay-tempus commented on examples/hallmarks_of_cancer.py
> +        if self.config.name == _DATASETNAME:
```suggestion
        if self.config.name == "source":
```

2022-02-25 18:36 UTC, galtay-tempus commented on examples/hallmarks_of_cancer.py
> +            if self.config.name == _DATASETNAME:
```suggestion
            if self.config.name == "source":        
```

2022-02-25 20:59 UTC, sunnnymskang commented on examples/hallmarks_of_cancer.py
> +_VERSION = "1.0.0"
```suggestion
_SOURCE_VERSION = "1.0.0"
```

2022-02-25 21:00 UTC, sunnnymskang commented on examples/hallmarks_of_cancer.py
> +    VERSION = datasets.Version(_VERSION)
```suggestion
    VERSION = datasets.Version(_SOURCE_VERSION)
```

2022-02-25 21:01 UTC, sunnnymskang requested changes
With these changes, I think it's ready to be merged

2022-02-27 04:57 UTC, debajyotidatta commented
I think this is good to merge. Are we waiting for something?

2022-02-27 17:27 UTC, galtay approved these changes
looks good to me

2022-02-27 17:28 UTC, galtay commented
going to merge this and we can address any problems that come up when unit tests are applied in subsequent PRs

2022-02-27 17:28 UTC, merged