Closes #854
bigscience-workshop/biomedical pull request #855
Opened 2023-01-05 13:14 UTC by Miking98

Add the Paragraph-Level Simplification of Medical Texts dataset. Closes #854

### Checkbox

- [X] Confirm that this PR is linked to the dataset issue.
- [X] Create the dataloader script `biodatasets/my_dataset/my_dataset.py` (please use only lowercase and underscore for dataset naming).
- [X] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_BIGBIO_VERSION` variables.
- [X] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [X] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `BigBioConfig` for the source schema and one for a bigbio schema.
- [X] Confirm dataloader script works with `datasets.load_dataset` function.
- [X] Confirm that your dataloader script passes the test suite run with `python -m tests.test_bigbio biodatasets/my_dataset/my_dataset.py`.
- [X] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

2023-01-06 04:37 UTC, galtay commented
@Miking98 thanks for this contribution! we are in the middle of updating our contribution guidelines to support hub datasets. Can I ask that we hold off on merging this until the new guidelines are published and/or can you update your PR to include an implementation in the  `hub_repos` directory? 

this is the PR that has the new contribution guidelines https://github.com/bigscience-workshop/biomedical/pull/850

and this is an example of a PR contributing code to the `hub_repos` directory (but it wont be easily testable until the PR above is merged) https://github.com/bigscience-workshop/biomedical/pull/852

2023-01-06 05:17 UTC, Miking98 commented
Thanks for the note @galtay, makes sense! Will hold off until the new guidelines are published in that case, then will revise and submit a new pull request once updated to abide by them. Thanks!

2023-01-14 18:09 UTC, galtay commented
hello @Miking98 thanks for your patience! we have a new `CONTRIBUTING.md` file now (https://github.com/bigscience-workshop/biomedical/blob/main/CONTRIBUTING.md) and I was wondering if you'd help us try it out. Please ping me if there are any issues and I'll help get this dataset loader in.

2023-01-31 01:44 UTC, Miking98 commented
Thanks for the note @galtay ! I just went through the revised Contributing doc and updated my pull request accordingly -- please let me know your thoughts

2024-08-23 14:45 UTC, phlobo requested changes
Thank your for the PR! Happy to merge after some very minor revisions.

2024-08-23 14:45 UTC, phlobo commented on bigbio/hub/hub_repos/medparasimp/__init__.py
Can this file be removed?

2024-08-23 14:45 UTC, phlobo commented on bigbio/hub/hub_repos/medparasimp/medparasimp.py
> +from bigbio.utils import schemas
The schema needs to be importend from `.bigbiohub` rather than bigbio (which is not available when loading from the HF hub)

2024-08-23 14:45 UTC, phlobo commented on bigbio/hub/hub_repos/medparasimp/medparasimp.py
> +            for idx, (source, target) in enumerate(zip(sources, targets)):
Code for source and bigbio_t2t seems to be identical, can you merge these code blocks into one to avoid duplication?

2024-08-23 14:45 UTC, phlobo commented on bigbio/hub/hub_repos/medparasimp/README.md
> +# Dataset Card for SciTail
Please update the name of the dataset

2024-10-21 09:08 UTC, phlobo commented
@mariosaenger I made some minor fixes myself, could you please review this PR?

2024-10-21 09:19 UTC, phlobo approved these changes

2024-10-23 10:27 UTC, mariosaenger approved these changes
LGTM. Thanks to all contributors.

2024-10-23 10:27 UTC, merged