Closes #873 and revises #874
bigscience-workshop/biomedical pull request #876
Opened 2023-02-22 11:43 UTC by WangXII

Closes https://github.com/bigscience-workshop/biomedical/issues/873 and revises https://github.com/bigscience-workshop/biomedical/pull/874 - Wrong entity offsets in the tmvar_v3 datasets

Wrong offsets in PMID 21904390 are already present in the source file https://ftp.ncbi.nlm.nih.gov/pub/lu/tmVar3/tmVar3Corpus.txt

Solution: Manually corrected the wrong offsets in PMID 21904390 as the wrong offsets do not seem to follow any pattern.

Compared to https://github.com/bigscience-workshop/biomedical/pull/874, this pull request reverts the offsets in the standard 'source' dataset back to original (but wrong) offsets provided by the original dataset and adds a new 'source_fixed' dataset with corrected offsets

### Checkbox

- [x] Confirm that this PR is linked to the dataset issue.
- [x] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `BigBioConfig` for the source schema and one for a bigbio schema.
- [x] Confirm dataloader script works with `datasets.load_dataset` function.
- [x] Confirm that your dataloader script passes the test suite run with `python -m tests.test_bigbio_hub <dataset_name> [--data_dir /path/to/local/data] --test_local`.

2023-03-14 15:30 UTC, leonweber requested changes
Imho this can be merged after the two comments have been resolved. Please also update to the lastest version of main. At the moment there is a conflict that prevents merging.

2023-03-14 15:30 UTC, leonweber commented on bigbio/hub/hub_repos/tmvar_v3/tmvar_v3.py
> -                        "type": [mention.type],
Same here: Is the change from sequence to single value intended here?

2023-03-14 16:16 UTC, WangXII commented
Thanks for the review @leonweber. Looking into the merge conflict, the branch is already up-to-date with main. It seems more like a simple change that the automatic merging strategies fails to recognize. The branch version adds an if-clause to just show the fixed annotations in the source version if the user explicitly requests it ("_source_fixed" vs "_source")

```
<<<<<<< tmvar_v3_fix
                if "_fixed" in self.config.name:
                    document["entities"] = self._correct_wrong_offsets(
                        document["entities"], doc.pmid
                    )
=======
                document["entities"] = self._correct_wrong_offsets(
                    document["entities"], doc.pmid
                )
>>>>>>> main
```

2023-03-14 16:26 UTC, WangXII commented on bigbio/hub/hub_repos/tmvar_v3/tmvar_v3.py
> -                        "semantic_type_id": [mention.type],
The goal is to bring the datatype of semantic_type_id into line with all other datasets where only a single value is used to hold the type (see https://github.com/bigscience-workshop/biomedical/blob/62fb81c8b24f692fbae675d11c545dd31dbc3eb5/bigbio/hub/hub_repos/bioinfer/bioinfer.py#L124 and https://github.com/bigscience-workshop/biomedical/blob/62fb81c8b24f692fbae675d11c545dd31dbc3eb5/bigbio/hub/hub_repos/nlm_gene/nlm_gene.py#L123). I've also checked that the dataset does not contain annotations with multiple semantic_type_id to be the reason for the sequence. However, if there was a rationale to let some semantic_type_id be sequences and some not then we can easily revert this change.

2023-03-15 15:28 UTC, leonweber approved these changes

2023-03-15 15:29 UTC, leonweber commented
@mariosaenger Can you review this please?

2024-10-12 17:33 UTC, mariosaenger approved these changes

2024-10-12 17:35 UTC, merged